FROM golang:1.23 AS builder
WORKDIR /app
COPY backend/go.mod .
COPY backend/go.sum .
COPY backend .
RUN go mod download

RUN echo "Trigger" 
RUN ls
WORKDIR /app/cmd
RUN ls

WORKDIR /app
RUN ls

RUN go build -o /app/backend ./cmd/main.go

FROM ubuntu:22.04
RUN mkdir /app
WORKDIR /app
COPY --from=builder /app/backend .
RUN chmod -R +x .

ENTRYPOINT ["/app/backend"]